CREATE TABLE Word (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    word VARCHAR(255) NOT NULL,
    translation VARCHAR(255) NOT NULL
);
CREATE TABLE texts (
    id SERIAL PRIMARY KEY,
    content TEXT NOT NULL
);